// <auto-generated />
using System;
using Cacahuate.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cacahuate.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713132941_AddAppointmentSignatures")]
    partial class AddAppointmentSignatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AvailabilityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EnRouteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("InProgressAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParentSignature")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ParentSignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProgressAchievements")
                        .HasColumnType("text");

                    b.Property<string>("ProgressAreasToReinforce")
                        .HasColumnType("text");

                    b.Property<string>("ProgressBehavior")
                        .HasColumnType("text");

                    b.Property<string>("ProgressCommunication")
                        .HasColumnType("text");

                    b.Property<string>("ProgressNotes")
                        .HasColumnType("text");

                    b.Property<string>("ProgressObjectives")
                        .HasColumnType("text");

                    b.Property<int?>("ProgressParticipationLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ProgressRecommendations")
                        .HasColumnType("text");

                    b.Property<string>("ProgressSensoryResponse")
                        .HasColumnType("text");

                    b.Property<string>("ProgressSocialInteraction")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProgressUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TherapistId")
                        .HasColumnType("uuid");

                    b.Property<string>("TherapistSignature")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TherapistSignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TherapistId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormFieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormFieldId");

                    b.HasIndex("FormSubmissionId");

                    b.ToTable("FormAnswers");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByAdminUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.HasIndex("PatientId");

                    b.ToTable("FormAssignments");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormTemplateId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Options")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("FormFields");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TherapistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("TherapistId");

                    b.HasIndex("FormAssignmentId", "AppointmentId")
                        .IsUnique();

                    b.ToTable("FormSubmissions");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Therapist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SessionDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Therapists");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.TherapistAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("SessionDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TherapistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TherapistId");

                    b.ToTable("TherapistAvailabilities");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.TherapistRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<Guid>("TherapistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("TherapistId");

                    b.ToTable("TherapistRatings");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Appointment", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.TherapistAvailability", "Availability")
                        .WithMany("Appointments")
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cacahuate.DataAccess.Entities.Parent", "Parent")
                        .WithMany("Appointments")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cacahuate.DataAccess.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cacahuate.DataAccess.Entities.Therapist", "Therapist")
                        .WithMany("Appointments")
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Availability");

                    b.Navigation("Parent");

                    b.Navigation("Patient");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormAnswer", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.FormField", "FormField")
                        .WithMany("Answers")
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cacahuate.DataAccess.Entities.FormSubmission", "FormSubmission")
                        .WithMany("Answers")
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormField");

                    b.Navigation("FormSubmission");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormAssignment", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.FormTemplate", "FormTemplate")
                        .WithMany("Assignments")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cacahuate.DataAccess.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormTemplate");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormField", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.FormTemplate", "FormTemplate")
                        .WithMany("Fields")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormSubmission", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.Appointment", "Appointment")
                        .WithOne("FormSubmission")
                        .HasForeignKey("Cacahuate.DataAccess.Entities.FormSubmission", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cacahuate.DataAccess.Entities.FormAssignment", "FormAssignment")
                        .WithMany("Submissions")
                        .HasForeignKey("FormAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cacahuate.DataAccess.Entities.Therapist", "Therapist")
                        .WithMany()
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("FormAssignment");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Notification", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Parent", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.User", "User")
                        .WithOne("Parent")
                        .HasForeignKey("Cacahuate.DataAccess.Entities.Parent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Patient", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.Parent", "Parent")
                        .WithMany("Patients")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.RefreshToken", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Therapist", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.User", "User")
                        .WithOne("Therapist")
                        .HasForeignKey("Cacahuate.DataAccess.Entities.Therapist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.TherapistAvailability", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.Therapist", "Therapist")
                        .WithMany("Availabilities")
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.TherapistRating", b =>
                {
                    b.HasOne("Cacahuate.DataAccess.Entities.Appointment", "Appointment")
                        .WithOne("Rating")
                        .HasForeignKey("Cacahuate.DataAccess.Entities.TherapistRating", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cacahuate.DataAccess.Entities.Parent", "Parent")
                        .WithMany("Ratings")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cacahuate.DataAccess.Entities.Therapist", "Therapist")
                        .WithMany("Ratings")
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Parent");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Appointment", b =>
                {
                    b.Navigation("FormSubmission");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormAssignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormField", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormSubmission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.FormTemplate", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Parent", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Patients");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.Therapist", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.TherapistAvailability", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Cacahuate.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Parent");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Therapist");
                });
#pragma warning restore 612, 618
        }
    }
}
